### ISSUE TITLE
Module not found error when updating library through npm

### ISSUE THREAD

**Issue by federicochiesa** [inrupt/solid-client-js#1231]
### Bug description

If I update my solid client library(from 1.10.0 to the latest one which is 1.11.0) through npm webpack stops working and gives a "Module not found" error:
```
ERROR in ./src/index.js 3:0-85
Module not found: Error: Can't resolve '@inrupt/solid-client/access/universal' in '/Applications/MAMP/htdocs/soliddashboard/src'
resolve '@inrupt/solid-client/access/universal' in '/Applications/MAMP/htdocs/soliddashboard/src'
  Parsed request is a module
  using description file: /Applications/MAMP/htdocs/soliddashboard/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Applications/MAMP/htdocs/soliddashboard/src/node_modules doesn't exist or is not a directory
      looking for modules in /Applications/MAMP/htdocs/soliddashboard/node_modules
        existing directory /Applications/MAMP/htdocs/soliddashboard/node_modules/@inrupt/solid-client
          using description file: /Applications/MAMP/htdocs/soliddashboard/node_modules/@inrupt/solid-client/package.json (relative path: .)
            using exports field: ./dist/access/universal.mjs
              using description file: /Applications/MAMP/htdocs/soliddashboard/node_modules/@inrupt/solid-client/package.json (relative path: ./dist/access/universal.mjs)
                no extension
                  Field 'browser' doesn't contain a valid alias configuration
                  /Applications/MAMP/htdocs/soliddashboard/node_modules/@inrupt/solid-client/dist/access/universal.mjs doesn't exist
                .js
                  Field 'browser' doesn't contain a valid alias configuration
                  /Applications/MAMP/htdocs/soliddashboard/node_modules/@inrupt/solid-client/dist/access/universal.mjs.js doesn't exist
                .json
                  Field 'browser' doesn't contain a valid alias configuration
                  /Applications/MAMP/htdocs/soliddashboard/node_modules/@inrupt/solid-client/dist/access/universal.mjs.json doesn't exist
                .wasm
                  Field 'browser' doesn't contain a valid alias configuration
                  /Applications/MAMP/htdocs/soliddashboard/node_modules/@inrupt/solid-client/dist/access/universal.mjs.wasm doesn't exist
                as directory
                  /Applications/MAMP/htdocs/soliddashboard/node_modules/@inrupt/solid-client/dist/access/universal.mjs doesn't exist
      /Applications/MAMP/htdocs/node_modules doesn't exist or is not a directory
      /Applications/MAMP/node_modules doesn't exist or is not a directory
      /Applications/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory

webpack 5.51.1 compiled with 1 error in 1596 ms
ℹ ｢wdm｣: Failed to compile.
```

### To Reproduce

1. Install 1.10.0
2. Update to 1.11.0
3. start webpack

### Environment

```
% npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers

  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 2.10 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.5.0 - ~/.nvm/versions/node/v16.5.0/bin/node
    npm: 7.19.1 - ~/.nvm/versions/node/v16.5.0/bin/npm
  Browsers:
    Firefox: 91.0.2
    Safari: 14.1.1
  npmPackages:
    @inrupt/solid-client: ^1.11.1-fix1226-null-getdate-1169648447-4070-1629965841.0 => 1.11.1-fix1226-null-getdate-1169648447-4070-1629965841.0 
    @inrupt/solid-client-authn-browser: ^1.9.1 => 1.11.2 
    @inrupt/vocab-common-rdf: ^0.7.5 => 0.7.5 
    buffer: ^6.0.3 => 6.0.3 
    css-loader: ^6.1.0 => 6.2.0 
    style-loader: ^3.1.0 => 3.2.1 
    uuid: ^8.3.2 => 8.3.2 
    webpack: ^5.45.1 => 5.51.1 
    webpack-cli: ^4.7.2 => 4.8.0 
    webpack-dev-server: ^3.11.2 => 3.11.2 
  npmGlobalPackages:
    browserify: 17.0.0
    npm: 7.19.1
```

**Comment by federicochiesa** [comment]
I tried creating a new app from scratch and it's giving me the same error. The libraries I'm importing in my code are: 
```js
import { handleIncomingRedirect, login, fetch, getDefaultSession } from "@inrupt/solid-client-authn-browser";
import { getSolidDataset, saveSolidDatasetAt, getThing, setThing, getStringNoLocale, setStringNoLocale, saveFileInContainer, getSourceUrl, setDate, setUrl, buildThing, createThing, getThingAll, getDate, getUrl} from "@inrupt/solid-client";
import {getAgentAccess, setAgentAccess} from "@inrupt/solid-client/access/universal";
import { v4 as uuidv4 } from 'uuid';
```

**Comment by NSeydoux** [comment]
Thanks for reporting this. I can reproduce the issue, so I'll try to see what can resolve it. In the meantime, if you need features from the `1.11.0` release, you can use the deprecated object export: 
```
import { access } from "@inrupt/solid-client";
const {getAgentAccess, setAgentAccess} = access;
```
The submodule import that you are using is the recommanded one, but if the deprecated one can unblock you temporarily...

**Comment by NSeydoux** [comment]
PR #1238 should resolve the issue. Can you confirm that using the patched version with `npm install @inrupt/solid-client@fix1231-submodule-import` leads to a correct behaviour ?

**Comment by federicochiesa** [comment]
Yes! It now works on 1.11.0, though this version doesn't fix the dates being null problem in #1226, is this expected behaviour?

**Comment by NSeydoux** [comment]
Mmh I think the fix have been included, but what I'll do is release a patch version so that both fixes are in the `@latest` release, which should set things right.

**Comment by NSeydoux** [comment]
`@inrupt/solid-client@1.11.1` should contain both fixes. Let me know if the issue persists :)
